[package]
name = "moai_gltf"
version = "0.0.1"
edition = "2021"
description = "Moai Framework GLTF Model Loader"
repository = "https://github.com/bpm-mcgill/moai"
license = "GPL-3.0+"
keywords = ["moai"]

[dependencies]
gltf = "1.1.0"