[package]
name = "demos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glfw = "0.51.0"
env_logger = "0.10.0"
renderer = { path="../renderer" }
sc_window = { path="../sc_window" }